apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cicd
bases:
  - ../../../base/network-policy
resources:
  - namespace.yaml
  - image-puller-rolebinding.yaml
patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: cicd-image-puller
    path: image-puller-rolebinding-patch.yaml