apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: petclinic-uat
bases:
  - ../../../base/network-policy
  - ../../../base/resource-quotas-limits
  - ../../../base/role-bindings  
resources:
  - namespace.yaml
  - developer-rolebinding.yaml
  - quay-pull-sealedsecret.json
